version: '3.9'
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: docker/php-fpm
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=mysql"
            - "MYSQL_USER=mysql"
            - "MYSQL_PASSWORD=mysql"
            - "MYSQL_DATABASE=keyua"
        ports:
            - "33061:3306"
